/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.ejercicio2_area_perimetro;

import javax.swing.JOptionPane;

/**
 *
 * @author elton
 */
public class Ejercicio2_area_perimetros extends javax.swing.JFrame {

    /**
     * Creates new form Ejercicio2_area_perimetros
     */
    public Ejercicio2_area_perimetros() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        base = new javax.swing.JTextField();
        Rec_perimetro = new javax.swing.JRadioButton();
        Rec_area = new javax.swing.JRadioButton();
        resultado = new javax.swing.JTextField();
        letrero1 = new javax.swing.JLabel();
        Cir_perimetro = new javax.swing.JRadioButton();
        Cir_area1 = new javax.swing.JRadioButton();
        letrero2 = new javax.swing.JLabel();
        altura = new javax.swing.JTextField();
        salir = new javax.swing.JRadioButton();
        letrero3 = new javax.swing.JLabel();
        radio = new javax.swing.JTextField();
        mostrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        base.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                baseActionPerformed(evt);
            }
        });

        buttonGroup1.add(Rec_perimetro);
        Rec_perimetro.setText("Calcular el área de un rectángulo.");
        Rec_perimetro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Rec_perimetroMouseClicked(evt);
            }
        });
        Rec_perimetro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Rec_perimetroActionPerformed(evt);
            }
        });

        buttonGroup1.add(Rec_area);
        Rec_area.setText("Calcular el perímetro de un rectángulo.");
        Rec_area.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Rec_areaActionPerformed(evt);
            }
        });

        resultado.setEditable(false);
        resultado.setText("Resultado:");
        resultado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resultadoActionPerformed(evt);
            }
        });

        letrero1.setText("Ingrese su base en cm");

        buttonGroup1.add(Cir_perimetro);
        Cir_perimetro.setText("Calcular el área de un circulo.");
        Cir_perimetro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cir_perimetroActionPerformed(evt);
            }
        });

        buttonGroup1.add(Cir_area1);
        Cir_area1.setText("Calcular el perímetro de un circulo.");
        Cir_area1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cir_area1ActionPerformed(evt);
            }
        });

        letrero2.setText("Ingrese su altura en cm");

        altura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alturaActionPerformed(evt);
            }
        });

        salir.setText("Salir.");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });

        letrero3.setText("Ingrese su radio en cm");

        radio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioActionPerformed(evt);
            }
        });

        mostrar.setText("Mostrar");
        mostrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mostrarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(resultado, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(letrero2, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(altura, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(letrero1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(base, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(letrero3, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(radio, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(Rec_perimetro, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Cir_perimetro, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(salir))
                    .addComponent(Cir_area1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(mostrar)
                        .addComponent(Rec_area)))
                .addContainerGap(124, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(Rec_perimetro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Rec_area)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Cir_perimetro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Cir_area1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(salir)
                .addGap(9, 9, 9)
                .addComponent(mostrar)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(letrero3)
                    .addComponent(radio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(letrero1)
                    .addComponent(base, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(letrero2)
                    .addComponent(altura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(resultado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void baseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_baseActionPerformed

    }//GEN-LAST:event_baseActionPerformed
private void actualizarCampos() {
    // Habilitar/deshabilitar según el botón seleccionado
    if (Rec_perimetro.isSelected() || Rec_area.isSelected()) {
        base.setEnabled(true);
        altura.setEnabled(true);
        radio.setEnabled(false);
    } else if (Cir_perimetro.isSelected() || Cir_area1.isSelected()) {
        base.setEnabled(false);
        altura.setEnabled(false);
        radio.setEnabled(true);
    } else {
        // Si no hay nada seleccionado, habilita todo o deshabilita todo según prefieras
        base.setEnabled(false);
        altura.setEnabled(false);
        radio.setEnabled(false);
    }
}
    private void Rec_perimetroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Rec_perimetroActionPerformed
        
    }//GEN-LAST:event_Rec_perimetroActionPerformed

    private void resultadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resultadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_resultadoActionPerformed

    private void Cir_perimetroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cir_perimetroActionPerformed
        
    }//GEN-LAST:event_Cir_perimetroActionPerformed

    private void Cir_area1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cir_area1ActionPerformed
         
    }//GEN-LAST:event_Cir_area1ActionPerformed

    private void Rec_perimetroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Rec_perimetroMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_Rec_perimetroMouseClicked

    private void alturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alturaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_alturaActionPerformed

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
                                             
        System.exit(0); // Termina el programa
  
    }//GEN-LAST:event_salirActionPerformed

    private void radioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioActionPerformed

    private void Rec_areaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Rec_areaActionPerformed
        
    }//GEN-LAST:event_Rec_areaActionPerformed

    private void mostrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mostrarMouseClicked
        
    try {
        
        if (Rec_perimetro.isSelected()) {
            actualizarCampos();
            double b = Double.parseDouble(base.getText());
            double h = Double.parseDouble(altura.getText());
            double perimetro = 2 * (b + h);
            resultado.setText("Perímetro del rectángulo: " + perimetro + " cm");
        }
        
        else if (Rec_area.isSelected()) {
            actualizarCampos();
            double b = Double.parseDouble(base.getText());
            double h = Double.parseDouble(altura.getText());
            double area = b * h;
            resultado.setText("Área del rectángulo: " + area + " cm²");
        }
        
        else if (Cir_perimetro.isSelected()) {
            actualizarCampos();
            double r = Double.parseDouble(radio.getText());
            double pi = Math.PI;
            double area = pi * Math.pow(r, 2);
            resultado.setText("Área del círculo: " + area + " cm²");
        }
        
        else if (Cir_area1.isSelected()) {
            actualizarCampos();
            double r = Double.parseDouble(radio.getText());
            double pi = Math.PI;
            double perimetro = 2 * pi * r;
            resultado.setText("Perímetro del círculo: " + perimetro + " cm");
        } else {
            resultado.setText("Por favor, seleccione una opción.");
        }
    } catch (NumberFormatException e) {
        resultado.setText("ERROR VALOR INVALIDO");
    }
    }//GEN-LAST:event_mostrarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ejercicio2_area_perimetros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ejercicio2_area_perimetros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ejercicio2_area_perimetros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ejercicio2_area_perimetros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ejercicio2_area_perimetros().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Cir_area1;
    private javax.swing.JRadioButton Cir_perimetro;
    private javax.swing.JRadioButton Rec_area;
    private javax.swing.JRadioButton Rec_perimetro;
    private javax.swing.JTextField altura;
    private javax.swing.JTextField base;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.JLabel letrero1;
    private javax.swing.JLabel letrero2;
    private javax.swing.JLabel letrero3;
    private javax.swing.JButton mostrar;
    private javax.swing.JTextField radio;
    private javax.swing.JTextField resultado;
    private javax.swing.JRadioButton salir;
    // End of variables declaration//GEN-END:variables
}
