/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package piedra_papel_tijera_historial;

import java.util.Random;
import javax.swing.JOptionPane;
/**
 *
 * @author elton
 */
public class Ejercicio3_piedra_papel_tijeras extends javax.swing.JFrame {
    private int cpuvic = 0;
    private int jugavic = 0;
    private int empate = 0;
    /**
     * Creates new form Ejercicio3_piedra_papel_tijeras
     */
    public Ejercicio3_piedra_papel_tijeras() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        salir = new javax.swing.JRadioButton();
        piedra = new javax.swing.JRadioButton();
        papel = new javax.swing.JRadioButton();
        resultado = new javax.swing.JTextField();
        tijera = new javax.swing.JRadioButton();
        mostrar = new javax.swing.JButton();
        Historial = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        salir.setText("Salir.");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });

        buttonGroup1.add(piedra);
        piedra.setText("Piedra");
        piedra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                piedraMouseClicked(evt);
            }
        });
        piedra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                piedraActionPerformed(evt);
            }
        });

        buttonGroup1.add(papel);
        papel.setText("Papel");
        papel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                papelActionPerformed(evt);
            }
        });

        resultado.setEditable(false);
        resultado.setText("Resultado:");
        resultado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resultadoActionPerformed(evt);
            }
        });

        buttonGroup1.add(tijera);
        tijera.setText("Tijera");
        tijera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tijeraActionPerformed(evt);
            }
        });

        mostrar.setText("Mostrar");
        mostrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mostrarMouseClicked(evt);
            }
        });

        Historial.setText("Historial");
        Historial.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HistorialMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(piedra, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tijera, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(papel))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(Historial)
                                .addGap(40, 40, 40))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(resultado, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(163, 163, 163)
                                .addComponent(mostrar))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(salir)))
                        .addGap(0, 32, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(piedra)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(papel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tijera)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Historial)
                .addGap(1, 1, 1)
                .addComponent(salir)
                .addGap(20, 20, 20)
                .addComponent(mostrar)
                .addGap(35, 35, 35)
                .addComponent(resultado, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed

        System.exit(0); // Termina el programa

    }//GEN-LAST:event_salirActionPerformed


    private void piedraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_piedraMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_piedraMouseClicked

    private void piedraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_piedraActionPerformed

    }//GEN-LAST:event_piedraActionPerformed

    private void papelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_papelActionPerformed

    }//GEN-LAST:event_papelActionPerformed

    private void resultadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resultadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_resultadoActionPerformed

    private void tijeraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tijeraActionPerformed

    }//GEN-LAST:event_tijeraActionPerformed

    private void mostrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mostrarMouseClicked
    String[] opciones = {"piedra", "papel", "tijera"};
    Random random = new Random();
    int cpu = random.nextInt(opciones.length);
    String eleccionCPU = opciones[cpu];
    String eleccionJugador = "";

    if (piedra.isSelected()) {
        eleccionJugador = "piedra";
    } else if (papel.isSelected()) {
        eleccionJugador = "papel";
    } else if (tijera.isSelected()) {
        eleccionJugador = "tijera";
    } else {
        JOptionPane.showMessageDialog(this, "Seleccione una opción.");
        return;
    }

    if (eleccionJugador.equals(eleccionCPU)) {
        empate++;
        resultado.setText("Jugador: " + eleccionJugador + ". CPU: " + eleccionCPU + ", Resultado: Empate");
    } else if (
        (eleccionJugador.equals("piedra") && eleccionCPU.equals("tijera")) ||
        (eleccionJugador.equals("papel") && eleccionCPU.equals("piedra")) ||
        (eleccionJugador.equals("tijera") && eleccionCPU.equals("papel"))
    ) {
        jugavic++;
        resultado.setText("Jugador: " + eleccionJugador + ". CPU: " + eleccionCPU + ", Resultado: Ganaste");
    } else {
        cpuvic++;
        resultado.setText("Jugador: " + eleccionJugador + ". CPU: " + eleccionCPU + ", Resultado: Gana la CPU");
    }
    }//GEN-LAST:event_mostrarMouseClicked

    private void HistorialMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HistorialMouseClicked
    JOptionPane.showMessageDialog(this, 
        "Historial:\n" + 
        "Victorias del jugador: " + jugavic + "\n" + 
        "Victorias de la CPU: " + cpuvic + "\n" + 
        "Empates: " + empate); 
    }//GEN-LAST:event_HistorialMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ejercicio3_piedra_papel_tijeras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ejercicio3_piedra_papel_tijeras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ejercicio3_piedra_papel_tijeras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ejercicio3_piedra_papel_tijeras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ejercicio3_piedra_papel_tijeras().setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Historial;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton mostrar;
    private javax.swing.JRadioButton papel;
    private javax.swing.JRadioButton piedra;
    private javax.swing.JTextField resultado;
    private javax.swing.JRadioButton salir;
    private javax.swing.JRadioButton tijera;
    // End of variables declaration//GEN-END:variables
}
